# Generated by Django 2.2.4 on 2019-10-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_it', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='aisle_id',
            field=models.ManyToManyField(blank=True, related_name='store_aisles', to='shop_it.Aisle'),
        ),
    ]
