# Generated by Django 2.2.4 on 2019-10-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_it', '0002_auto_20191006_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisle',
            name='category_id',
            field=models.ManyToManyField(blank=True, related_name='categories', to='shop_it.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='product_id',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop_it.Product'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='shopping_list_products', to='shop_it.Product'),
        ),
    ]
