# Generated by Django 2.2.4 on 2019-10-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_it', '0003_auto_20191008_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='date',
        ),
    ]
