# Generated by Django 2.2.4 on 2019-10-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_it', '0006_auto_20191008_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='lists', to='shop_it.Product'),
        ),
    ]
