# Generated by Django 2.2.4 on 2019-10-08 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_it', '0007_auto_20191008_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='product',
            new_name='products',
        ),
    ]
