# Generated by Django 2.2.4 on 2019-10-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_it', '0010_auto_20191015_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
