# Generated by Django 2.2.4 on 2019-10-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_it', '0013_auto_20191015_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
